// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	api4 "github.com/rizxfrog/VanPanelBackend/internal/files/api"
	dao2 "github.com/rizxfrog/VanPanelBackend/internal/files/dao"
	service3 "github.com/rizxfrog/VanPanelBackend/internal/files/service"
	api2 "github.com/rizxfrog/VanPanelBackend/internal/not_auth/api"
	service2 "github.com/rizxfrog/VanPanelBackend/internal/not_auth/service"
	"github.com/rizxfrog/VanPanelBackend/internal/system/api"
	"github.com/rizxfrog/VanPanelBackend/internal/system/dao"
	"github.com/rizxfrog/VanPanelBackend/internal/system/service"
	api3 "github.com/rizxfrog/VanPanelBackend/internal/terminal/api"
	"github.com/rizxfrog/VanPanelBackend/pkg/jwt"
	"github.com/rizxfrog/VanPanelBackend/pkg/sse"
	"github.com/rizxfrog/VanPanelBackend/pkg/terminal"
)

import (
	_ "github.com/google/wire"
)

// Injectors from wire.go:

func ProvideCmd() *Cmd {
	cmdable := InitRedis()
	handler := jwt.NewJWTHandler(cmdable)
	logger := InitLogger()
	db := InitDB()
	roleDAO := dao.NewRoleDAO(db)
	roleService := service.NewRoleService(roleDAO, logger)
	auditDAO := dao.NewAuditDAO(db)
	auditService := service.NewAuditService(auditDAO, logger)
	v := InitMiddlewares(handler, logger, roleService, auditService)
	userDAO := dao.NewUserDAO(db, logger)
	userService := service.NewUserService(userDAO, roleDAO, logger)
	userHandler := api.NewUserHandler(userService, handler)
	apiDAO := dao.NewApiDAO(db, logger)
	apiService := service.NewApiService(logger, apiDAO)
	apiHandler := api.NewApiHandler(apiService)
	roleHandler := api.NewRoleHandler(roleService)
	systemService := service.NewSystemService(logger, cmdable)
	systemHandler := api.NewSystemHandler(systemService)
	notAuthService := service2.NewNotAuthService(logger)
	notAuthHandler := api2.NewNotAuthHandler(notAuthService)
	auditHandler := api.NewAuditHandler(auditService, logger)
	localAdapter := ProvideTerminalLocalAdapter()
	config := ProvideTerminalConfig()
	terminalService := ProvideTerminalService(logger, localAdapter, config)
	terminalHandler := api3.NewTerminalHandler(terminalService, logger)
	managerConfig := ProvideFileManagerConfig()
	fileService := service3.NewFileService(logger, managerConfig)
	fileHandler := api4.NewFileHandler(fileService)
	fileShareDAO := dao2.NewFileShareDAO(db, logger)
	fileShareService := service3.NewFileShareService(logger, fileShareDAO, managerConfig)
	fileShareHandler := api4.NewFileShareHandler(fileShareService)
	shareAccessHandler := api4.NewShareAccessHandler(fileShareService)
	agentDAO := ProvideAgentDAO(db, logger)
	toolManager := ProvideAgentToolManager(agentDAO, logger)
	agentRiskConfig := ProvideAgentRiskConfig()
	evaluator := ProvideAgentRiskEvaluator(agentRiskConfig)
	store := ProvideAgentAuditStore(agentDAO, logger)
	agentConfig := ProvideAgentConfig()
	stage := ProvideAgentPipeline(agentDAO, logger)
	agentService := ProvideAgentService(agentDAO, toolManager, evaluator, store, agentConfig, logger, stage)
	agentHubConfig := ProvideAgentHubConfig()
	hubService := ProvideHubService(agentDAO, toolManager, agentHubConfig, logger)
	handler2 := ProvideAgentHandler(agentService, hubService)
	engine := InitGinServer(v, userHandler, apiHandler, roleHandler, systemHandler, notAuthHandler, auditHandler, terminalHandler, fileHandler, fileShareHandler, shareAccessHandler, handler2)
	cmd := &Cmd{
		Server: engine,
	}
	return cmd
}

// wire.go:

type Cmd struct {
	Server *gin.Engine
}

var HandlerSet = wire.NewSet(api.NewRoleHandler, api.NewApiHandler, api.NewAuditHandler, api.NewSystemHandler, api.NewUserHandler, api2.NewNotAuthHandler, api3.NewTerminalHandler, terminal.NewTerminalHandler, api4.NewFileHandler, api4.NewFileShareHandler, api4.NewShareAccessHandler, ProvideAgentHandler)

var ServiceSet = wire.NewSet(service.NewUserService, service.NewApiService, service.NewRoleService, service.NewAuditService, service.NewSystemService, service2.NewNotAuthService, service3.NewFileService, service3.NewFileShareService, ProvideFileManagerConfig,
	ProvideTerminalConfig,
	ProvideTerminalLocalAdapter,
	ProvideTerminalService,
)

var DaoSet = wire.NewSet(dao.NewUserDAO, dao.NewRoleDAO, dao.NewApiDAO, dao.NewAuditDAO, dao2.NewFileShareDAO, ProvideAgentDAO)

var UtilSet = wire.NewSet(jwt.NewJWTHandler, sse.NewHandler)

var Injector = wire.NewSet(
	InitMiddlewares,
	InitGinServer,
	InitLogger,
	InitRedis,
	InitDB, wire.Struct(new(Cmd), "*"),
)

var AgentSet = wire.NewSet(
	ProvideAgentConfig,
	ProvideAgentRiskConfig,
	ProvideAgentHubConfig,
	ProvideAgentToolManager,
	ProvideAgentRiskEvaluator,
	ProvideAgentAuditStore,
	ProvideAgentService,
	ProvideHubService,
	ProvideAgentGuardChain,
	ProvideAgentMemoryProvider,
	ProvideAgentPipeline,
)
